# Generated by Django 4.0.1 on 2022-03-10 15:10

import django.core.validators
from django.db import migrations, models
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipproject',
            name='time_allocated_by_member',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2, 'le templs min aloué doit etre =5')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='timeallocated',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2, 'le templs min aloué doit etre =5')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[hub.models.emailValidator], verbose_name='Email'),
        ),
    ]
